locale = "zh-cn"
label = "简体中文"
weight = 9
title = "Qi QI's Website"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/favicon.png"
  secondaryLogo = "img/favicon.png"
  description = "my website"
[params.author]
  name = "Qi QI"
  image = "img/photo_mit_3.png"
  headline = "你好！我主要教授算法与博弈问题、人工智能、网络安全技术等课程。我的研究兴趣主要在算法、组合优化问题和博弈问题。专业领域包括算法博弈、机器学习和数据科学。我在美国密苏里哥伦比亚大学获得计算机科学哲学博士学位，我的导师是[Yi Shang](https://engineering.missouri.edu/faculty/yi-shang/)。我的电子邮件地址Email： qqi@hainanu.edu.cn"
  bio = "你好！我在海南大学计算机科学与技术学院教授算法与博弈问题、人工智能、网络安全技术等课程。我的研究兴趣主要在组合优化问题与博弈问题，相关应用在计算机科学、经济、社会、心理学、工业，和网络空间安全等领域。专业领域包括算法博弈、机器学习和数据科学。我在美国密苏里哥伦比亚大学获得计算机科学哲学博士学位，我的导师是[Yi Shang](https://engineering.missouri.edu/faculty/yi-shang/)。我的电子邮件地址Email： qqi@hainanu.edu.cn"
  links = [
    { x-twitter = "" },
    { github = "" },
  ]